export const productHuntDemoContractPrompt = 'Review every termination clause in this fictional agreement. Classify each as HIGH, MEDIUM, or LOW risk, highlight the exact evidence, explain the reason, and ask me to review unclear wording.';

export const productHuntDemoContractGuidelines = 'Synthetic demonstration only; this is not legal advice. HIGH: one-sided immediate termination or material exposure with no stated limit. MEDIUM: material terms, triggers, or notice periods are unclear or depend on context elsewhere in the agreement. LOW: mutual, bounded rights with a stated notice or cure period. Quote a short exact excerpt. Do not infer missing terms. Ask for human review when the wording or agreement context is insufficient.';
export const productHuntDemoContractFileName = 'fictional-termination-contract-live.pdf';

export const productHuntDemoFeedbackFileName = 'customer-feedback-demo.xlsx';

export const productHuntDemoFeedbackPrompt = 'Classify every customer feedback row. Add columns for Intent, Sentiment, Urgency, Evidence quote, Human review, and Review reason. Fill one result per Ticket ID, preserve the source columns, and send uncertain cases to human review.';

export const productHuntDemoFeedbackGuidelines = 'Synthetic ticket data only. Intent must be one of: Billing, Account access, Bug, Performance, Cancellation, Privacy / security, Feature request, Delivery, Other. Sentiment: Positive, Neutral, Negative, or Mixed. Urgency: P1 Critical for a suspected active account compromise, broad outage, confirmed data loss, or safety issue; P2 High for a blocked core workflow, active incorrect charge, or reported privacy/security incident; P3 Normal for a degraded workflow with a workaround; P4 Low for a feature request, general question, or cosmetic issue. Use Unknown when impact cannot be established from the row, and set Human review to Yes. Judge urgency from impact, not emotional tone; classify reports as reported, not independently verified. Copy a short exact quote into Evidence quote. Set Human review to Yes and explain why when the message is ambiguous, contradictory, or missing facts required by the rubric. Otherwise set No and leave Review reason blank. Do not infer customer details or facts not in the row.';

export const productHuntDemoChurnFileName = 'customer-churn-risk-demo.xlsx';

export const productHuntDemoChurnPrompt = 'Classify every synthetic customer as High, Medium, or Low churn risk. Fill one label in the existing blank Churn Risk column for each customer, preserve every source field, and ask me to review missing or conflicting evidence.';

export const productHuntDemoChurnGuidelines = 'Synthetic demonstration data only. Use the 2026-09-01 snapshot. `tickets` is the number of support tickets during the previous 90 days; `monthly_usage` is product activity hours during the previous 30 days; `last_login` is an ISO date. Write exactly one of High, Medium, or Low in Churn Risk. High: last login was 30 or more days before the snapshot and monthly usage is below 2 hours, OR there were at least 5 tickets and monthly usage is below 3 hours. Low: last login was within 14 days, monthly usage is at least 8 hours, and there was at most 1 ticket. Medium: every other complete, non-conflicting row. Use only the recorded values; name and plan are not risk signals. Preserve source cells and do not add output columns. If a required value is missing, invalid, or conflicting, leave that row’s Churn Risk blank and ask a human to review it instead of guessing.';
